# Generated by Django 4.1.6 on 2023-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogpost_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='maintitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
